younghun/django1/front/isagagae/isagagae/urls.py
from django.contrib import admin
from django.urls import path, include
import mainblog.views

urlpatterns = [
    # path('', mainblog.views.index, name='index'),
    path('',include('mainblog.urls'),name= 'mainblog'),
    path('admin/', admin.site.urls),
    path('',include('star.urls')),
    # path('map/', mainblog.views.showmap, name='showmap'),
    # path('memotest/', mainblog.views.memotest, name = 'memotest'),
    # path('deleteMemo/', mainblog.views.doneMemo, name = 'deleteMemo'),
    # path('savestar/', mainblog.views.savestar, name = 'savestar'),
    # path('service/',mainblog.views.service,name ='service')
#    path('result/',mainblog.views.result,name='result')
]

younghun/django1/front/isagagae/mainblog/urls.py
from django.urls import path, include
from . import views
from .views import CustomLoginView, RegisterPage
from django.contrib.auth.views import LogoutView


urlpatterns = [
    path('',views.index,name='index'),
    path('login/', CustomLoginView.as_view(), name='login'),
    path('logout/', LogoutView.as_view(next_page='login'), name='logout'),
    path('register/', RegisterPage.as_view(), name='register'),
    path('service/',include('star.urls',namespace='starfin')),
    # path('/service/showpinmap/',include('star.urls',namespace='showpinmap')),
    ]

younghun/django1/front/isagagae/star/urls.py
from django.urls import path
from . import views
app_name = 'star'
urlpatterns = [
    path('',views.starindex,name='star_index'),
    path('pinmap', views.showpinmap, name='pinmap'),
]

younghun/django1/front/isagagae/mainblog/models.py
from django.db import models
from django.core.validators import MinValueValidator, MaxValueValidator

# Create your models here.
class User(models.Model):
    user_name = models.CharField(max_length=20)
    user_email = models.EmailField(unique=True)
    user_password = models.CharField(max_length=100)
    user_validate = models.BooleanField(default=False)

class Memo(models.Model) :
    content = models.CharField(max_length=255)


class Star(models.Model) :
    id = models.IntegerField(primary_key=True)
    star_rate = models.IntegerField(db_column='rate', blank=True, null=True)
#
# class UserID(models.Model):
#     user_id = models.CharField(max_length=20)
#     class Meta:
#         managed = False
#         db_table = 'user'
# class PetShopSurvey(models.Model):
#     i_like_snakes = LikertField()

younghun/django1/front/isagagae/mainblog/views.py
from django.shortcuts import render, redirect
# from .models import Test
from django.http import HttpResponse
from django.urls import reverse
from .models import *
from django.views.generic.list import ListView
from django.views.generic.detail import DetailView
from django.views.generic.edit import CreateView, UpdateView, DeleteView, FormView
from django.urls import reverse_lazy

from django.contrib.auth.views import LoginView
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth import login
from django.contrib.auth.models import User







class CustomLoginView(LoginView):
    template_name = 'base/login.html'
    fields = '__all__'
    redirect_authenticated_user = True
    def get_success_url(self):
        return reverse_lazy('index')

class RegisterPage(FormView):
    template_name = 'base/register.html'
    form_class = UserCreationForm
    redirect_authenticated_user = True
    success_url = reverse_lazy('index')

    def form_valid(self,form):
        user = form.save()
        if user is not None:
            login(self.request, user)
        return super(RegisterPage, self).form_valid(form)

    def get(self, *args, **kwargs):
        if self.request.user.is_authenticated:
            return redirect('index')
        return super(RegisterPage, self).get(*args, **kwargs)

def index(request) :
    return render(request, 'index.html')

def service(request) :
   return render(request,'service.html')

def result(request) :
   return render(request,'result.html')



# def memotest(request) :
#     user_input_str = request.POST['inputContent']
#     # 사용자 인풋값이 new_memo라는 변수에 저장됨
#     new_memo = Memo(content = user_input_str)
#     new_memo.save()
#     return redirect(reverse('showblog'))
#     # return HttpResponse('memotest임! =>'+user_input_str)
#
# def doneMemo(request) :
#     done_memo_id = request.GET['memoNum']
#     print('완료한 memo의 id', done_memo_id)
#     memo = Memo.objects.get(id = done_memo_id)
#     memo.delete()
#     return redirect(reverse('showblog'))
#
# def savestar(request) :
#     user_input_star = request.POST['value']
#     new_star = Star(content = user_input_star)
#     new_star.save()
#     return redirect(reverse('showblog'))

younghun/django1/front/isagagae/mainblog/templates/index.html
<!DOCTYPE html>
<!--
	 by TEMPLATE STOCK
	templatestock.co @templatestock
	Released for free under the Creative Commons Attribution 3.0 license (templated.co/license)
-->

<html lang="en">
{% load static %}

    <head>
		<meta http-equiv="X-UA-Compatible" content="IE=edge">
		<meta name="viewport" content="width=device-width, initial-scale=1">
		<title>어디가냥? 이사가개!</title>
		<meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no">
		
		<!-- =====CSS====-->
		<!--<link href='http://fonts.googleapis.com/css?family=Open+Sans:400,300,700' rel='stylesheet' type='text/css'>-->
		<link rel="stylesheet" href="{% static 'css/style.css' %}" type="text/css" />
		<!-- Fontawesome아이콘 글씨 -->
		<link rel="stylesheet" href="{% static 'css/font-awesome.min.css' %}" type="text/css" />
		<!-- jQuery 플러그인 fancybox 팝업 -->
		<link rel="stylesheet" href="{% static 'css/jquery.fancybox.css' %}" type="text/css" />
		<!-- bootstrap.min -->
		<link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}" type="text/css" />
		<!-- jQuery터치응답 지원하는 플러그인 -->
		<link rel="stylesheet" href="{% static 'css/owl.carousel.css' %}" type="text/css" />
		<!-- jQuery슬라이드 플러그인-fullscreen-slit-slide -->
		<link rel="stylesheet" href="{% static 'css/slit-slider.css' %}" type="text/css" />
		<!-- css3动画库 -->
		<link rel="stylesheet" href="{% static 'css/animate.css' %}" type="text/css" />
		<!-- main样式文件 -->
		<link rel="stylesheet" href="{% static 'css/main.css' %}" type="text/css" />
		<!-- icofont -->
		<link rel="stylesheet" href="{% static 'css/icofont.css' %}" type="text/css" />
		<!-- H5 CSS3 浏览器兼容性处理 -->
        <script src='{% static "js/modernizr-2.6.2.min.js" %}'></script>

    </head>

    <body id="body">

        <!--固定的导航栏 -->
        <header id="navigation" class="navbar-inverse navbar-fixed-top animated-header" >
            <div class="container">
                <div class="navbar-header">

					<!-- logo -->
					<div class="navbar-brand">
						<a href="#body"><img src="{% static 'img/logo/logo.png'%}"></a>
					</div>
					<!-- /logo -->
                </div>
				<!-- main nav -->
                <nav class="collapse navbar-collapse navbar-right" role="navigation">
                    <ul class="nav navbar-nav">
                        <li id="nav"><a href="#body">Home</a></li>
                        <li id="nav"><a href="#about">About Us</a></li>
                        <li id="nav"><a href="#review">Review</a></li>
                        {% if request.user.is_authenticated %}
                        <li><a href="{% url 'starfin:star_index' %}">Service</a></li>
					    <li><a href="{% url 'logout' %}">Logout</a></li>
                        <li><a style="color:#1C304A;"><b>id:</b>{{ request.user }}</a></li>
                        {% else %}
                        <li><a href="{% url 'login' %}">Login</a></li>
                        {% endif %}
                    </ul>
                </nav>
				<!-- /main nav -->
				
            </div>
        </header>
        <!--고정 네비 끝-->
		
		<main class="site-content" role="main">
		
        <!--페이지 메인 슬라이드 -->
		
		<section id="home-slider">
            <div id="slider" class="sl-slider-wrapper">

				<div class="sl-slider">
				
					<div class="sl-slide" data-orientation="horizontal" data-slice1-rotation="-25" data-slice2-rotation="-25" data-slice1-scale="2" data-slice2-scale="2">

						<div class="bg-img bg-img-1"></div>

						<div class="slide-caption">
                            <div class="caption-content">
                                <h2 class="animated fadeInDown">어디가냥? 이사가개!</h2>
                                <span class="animated fadeInDown" style="text-shadow:1px 1px 1px #1C304A;">반려동물 양육 인프라 기반 이사 지역 추천 서비스</span>
                                <a href="{% url 'starfin:star_index' %}" class="btn btn-blue btn-effect">Service</a>
                            </div>
                        </div>
						
					</div>
					
					<div class="sl-slide" data-orientation="vertical" data-slice1-rotation="10" data-slice2-rotation="-15" data-slice1-scale="1.5" data-slice2-scale="1.5">
						<div class="bg-img bg-img-2"></div>
						<div class="slide-caption">
                            <div class="caption-content">
                                <h2>이사가냥? 알려줄개!</h2>
                                <span>내가 원하는 산업 시설이 많은 지역으로 맞춤 추천 서비스</span>
                                <a href="{% url 'register' %}" class="btn btn-blue btn-effect">Join US</a>
                            </div>
                        </div>
						
					</div>
					
					<div class="sl-slide" data-orientation="horizontal" data-slice1-rotation="3" data-slice2-rotation="3" data-slice1-scale="2" data-slice2-scale="1">
						<div class="bg-img bg-img-3"></div>
						<div class="slide-caption">
                            <div class="caption-content">
                                <h2>리얼 리뷰</h2>
                                <span>어디가냥?이사가개!를 이용한 사용자들의 솔직한 사용후기</span>
                                <a href="#Review" class="btn btn-blue btn-effect">Review</a>
                            </div>
                        </div>

					</div>

					<div class="sl-slide" data-orientation="vertical" data-slice1-rotation="10" data-slice2-rotation="-15" data-slice1-scale="1.5" data-slice2-scale="1.5">
						<div class="bg-img bg-img-4"></div>
						<div class="slide-caption">
                            <div class="caption-content">
                                <h2>다시가개!</h2>
                                <span>나에게 맞는 맞춤 지역 결과 보기</span>
                                <a href="#" class="btn btn-blue btn-effect">Result</a>
                            </div>
                        </div>

					</div>

				</div><!-- /sl-slider -->

                <!--轮播图箭头在大屏模式下显示-->
                <nav id="nav-arrows" class="nav-arrows hidden-xs hidden-sm ">
                    <a href="javascript:;" class="sl-prev">
                        <i class="fa fa-angle-left fa-3x"></i>
                    </a>
                    <a href="javascript:;" class="sl-next">
                        <i class="fa fa-angle-right fa-3x"></i>
                    </a>
                </nav>
                
				<!--轮播图小按在小屏模式下显示-->
				<nav id="nav-dots" class="nav-dots  hidden-md hidden-lg">
					<span class="nav-dot-current"></span>
					<span></span>
					<span></span>
				</nav>

			</div><!-- /slider-wrapper -->
		</section>

        <!--
        End Home SliderEnd
        ==================================== -->
			<!-- about section -->
         <section id="about" >
            <div class="container">
               <div class="row">
                     <div class="recent-works">
                        <h1>About Us</h1>
                        <div id="works">
                           <div class="work-item">
                              <br>
                              <p> <b style="font-size:23px;">어디가냥?이사가개!</b><br><br>저희는 반려동물과 함께 생활하는 <b>Pet-Family</b>들의 생활 가치를 증진하기 위한 사명과 미래를 위해 항상 노력하고 발전하는 지역 추천 플랫폼 입니다.</p>
                           </div>
                           <div class="work-item">
                              <br>
                              <p> <b style="font-size:23px;">Mission</b><br><br> 반려동물 양육 인프라 기반으로 지역을 추천해 줌으로써 보다 빠르고 편리한 결정을 내릴 수 있게 반려생활에 도움을 주는것 입니다.</p>
                           </div>
                           <div class="work-item">
                              <br>
                              <p> <b style="font-size:23px;">Vision</b><br><br> 이제는 가족의 일원이 되는 우리의 반려동물들과 고객님들의 더 나은 일상, 더 행복한 반려생활을 같이 꿈꾸며 항상 편리하고, 고객님들의 목소리를 반영하는 서비스를 제공하겠습니다.</p>
                           </div>
                        </div>
                  </div>
               </div>


                <div class = "col-xs-4 text-center wow animated zoomIn" data-wow-delay="0.3s">
                   <i class="icofont-medical-sign icofont-5x"></i>
                   <div class="feature-info">
                      <h4>Health</h4>
                      <p class="feature-description">반려동물의 건강을 책임질 <br>병원, 약국</p>
                   </div>
                 </div>

                 <div class = "col-xs-4 text-center wow animated zoomIn" data-wow-delay="0.3s">
                   <i class="icofont-paw icofont-5x"></i>
                   <div class="feature-info">
                      <h4>Play</h4>
                      <p class="feature-description">반려동물과 함께 뛰놀 수 있는 <br>놀이터, 공원</p>
                   </div>
                 </div>

                 <div class = "col-xs-4 text-center wow animated zoomIn" data-wow-delay="0.3s">
                   <i class="icofont-soup-bowl icofont-5x"></i>
                   <div class="feature-info">
                      <h4>Food</h4>
                      <p class="feature-description">반려동물과 함께 갈 수 있는 <br>식당 및 카페</p>
                   </div>
                 </div>

                 <div class = "col-xs-4 text-center wow animated zoomIn" data-wow-delay="0.6s">
                   <i class="icofont-dog-alt icofont-5x"></i>
                   <div class="feature-info">
                      <h4>Beauty </h4>
                      <p class="feature-description">반려동물을 예쁘게 단장할 <br>미용실</p>
                   </div>
                 </div>

                 <div class = "col-xs-4 text-center wow animated zoomIn" data-wow-delay="0.6s">
                   <i class="icofont-cat-dog icofont-5x"></i>
                   <div class="feature-info">
                      <h4>Life</h4>
                      <p class="feature-description">반려동물의 일상과 관련된 <br>펫택시, 동물용품판매점, <br>동물판매업, 사료제조업 </p>
                   </div>
                 </div>

                 <div class = "col-xs-4 text-center wow animated zoomIn" data-wow-delay="0.6s">
                   <i class="icofont-dog icofont-5x"></i>
                   <div class="feature-info">
                      <h4>Care</h4>
                      <p class="feature-description">반려동물 교육 및 위탁을 책임지는 <br>유치원, 호텔링</p>
                   </div>
                 </div>
            </div>
         </section>
			<!-- end About section>-->

						<!-- Testimonial section -->
			<section id="review" class="parallax">
				<div class="overlay">
					<div class="container">
						<div class="row">

							<div class="sec-title text-center white wow animated fadeInDown">
								<h2>사용자들의 REAL REAVIEW</h2>
							</div>

							<div id="testimonial" class=" wow animated fadeInUp">
								<div class="testimonial-item text-center">
									<img src="{%static 'img/review/m-1.png'%}" alt="Our Clients">
									<div class="clearfix">
										<span>문경미</span>
										<p> 평소 운동량이 많은 반려견과 함께 살고 있어, 산책할 곳이 필요했는데,'어디가냥?이사가개'를 이용해서 산책할 곳이 많은 곳으로 이사해서 요즘 1일 1산책 실천하고 있습니다!^^</p>
									</div>
								</div>
								<div class="testimonial-item text-center">
									<img src="{%static 'img/review/m-2.png'%}" alt="Our Clients">
									<div class="clearfix">
										<span>김희진</span>
										<p>예전에 댕댕이가 아플 때 병원에 늦게 가서 큰일 날 뻔한 적이 있는데, 이제 걸어서 갈 수 있는 병원이 있어, 반려 생활하는데 있어 너무 안심이 됩니다</p>
									</div>
								</div>
								<div class="testimonial-item text-center">
									<img src="{%static 'img/review/m-3.png'%}" alt="Our Clients">
									<div class="clearfix">
										<span>이동헌</span>
										<p>지방에서 살다가 이번에 취직을 해서 서울로 상경하게 되었는데, 서울에 대해 아무것도 몰라서 '어디가냥? 이사가개'를</p> <p>저희 반려견과 함께 살 수 있는 좋은 동네를 추천받았습니다. 고맙습니다 </p>
									</div>
								</div>
							</div>
						</div>
					</div>
				</div>
			</section>
			<!-- end Testimonial section -->

		</main>
		
		<footer id="footer">
			<div class="container">
				<div class="row text-center">
					<div class="footer-content">
						<p>Copyright &copy; 2021 Multi Campus Uhdirogayahazo</p>
					</div>
				</div>
			</div>
		</footer>
		
		<!-- Essential jQuery Plugins
		================================================== -->
		<!-- Main jQuery -->
		<script src='{% static "js/jquery-1.11.1.min.js" %}'></script>
		<!-- Twitter Bootstrap -->
        <!--<script src="js/bootstrap.min.js"></script>-->
		<!-- Single Page Nav -->
		<script src='{% static "js/jquery.singlePageNav.min.js" %}'></script>
		<!-- jquery.fancybox.pack -->
		<script src='{% static "js/jquery.fancybox.pack.js" %}'></script>
		<!-- Google Map API -->
		<script src="http://maps.google.com/maps/api/js?sensor=false"></script>
		<!-- Owl Carousel -->
		<script src='{% static "js/owl.carousel.min.js" %}'></script>
        <!-- jquery easing -->
		<script src='{% static "js/jquery.easing.min.js" %}'></script>
        <!-- Fullscreen slider -->
		<script src='{% static "js/jquery.slitslider.js" %}'></script>
		<script src='{% static "js/jquery.ba-cond.min.js" %}'></script>
		<!-- onscroll animation -->
		<script src='{% static "js/wow.min.js" %}'></script>
		<!-- Custom Functions -->
		<script src='{% static "js/main.js" %}'></script>
    </body>
</html>

younghun/django1/front/isagagae/mainblog/templates/result.html
<!DOCTYPE html>
<!--
	 by TEMPLATE STOCK
	templatestock.co @templatestock
	Released for free under the Creative Commons Attribution 3.0 license (templated.co/license)
-->

<html lang="en">
<!--{% load static %}-->

    <head>
		<meta http-equiv="X-UA-Compatible" content="IE=edge">
		<meta name="viewport" content="width=device-width, initial-scale=1">
		<title>어디가냥? 이사가개!</title>
		<meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no">
		
		<!-- =====CSS====-->
		<!--<link href='http://fonts.googleapis.com/css?family=Open+Sans:400,300,700' rel='stylesheet' type='text/css'>-->
		<link rel="stylesheet" href="{% static 'css/style.css' %}" type="text/css" />
		<!-- Fontawesome아이콘 글씨 -->
		<link rel="stylesheet" href="{% static 'css/font-awesome.min.css' %}" type="text/css" />
		<!-- jQuery 플러그인 fancybox 팝업 -->
		<link rel="stylesheet" href="{% static 'css/jquery.fancybox.css' %}" type="text/css" />
		<!-- bootstrap.min -->
		<link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}" type="text/css" />
		<!-- jQuery터치응답 지원하는 플러그인 -->
		<link rel="stylesheet" href="{% static 'css/owl.carousel.css' %}" type="text/css" />
		<!-- jQuery슬라이드 플러그인-fullscreen-slit-slide -->
		<link rel="stylesheet" href="{% static 'css/slit-slider.css' %}" type="text/css" />
		<!-- css3动画库 -->
		<link rel="stylesheet" href="{% static 'css/animate.css' %}" type="text/css" />
		<!-- main样式文件 -->
		<link rel="stylesheet" href="{% static 'css/main.css' %}" type="text/css" />
		<!-- test -->
		<link rel="stylesheet" href="{% static 'css/test.css' %}" type="text/css" />
		<!-- H5 CSS3 浏览器兼容性处理 -->
        <script src='{% static "js/modernizr-2.6.2.min.js" %}'></script>

    </head>

    <body id="body">

        <!--固定的导航栏 -->
        <header id="navigation" class="navbar-inverse navbar-fixed-top animated-header" >
            <div class="container">
                <div class="navbar-header">
                    <!-- responsive nav button -->
					<button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
						<span class="sr-only">Toggle navigation</span>
						<span class="icon-bar"></span>
						<span class="icon-bar"></span>
						<span class="icon-bar"></span>
                    </button>
					<!-- /responsive nav button -->
					
					<!-- logo -->
					<div class="navbar-brand">
						<a href="#body"><img src="{% static 'img/logo/logo.png'%}"></a>
					</div>
					<!-- /logo -->
                </div>
				<!-- main nav -->
                <nav class="collapse navbar-collapse navbar-right" role="navigation">
                    <ul id="nav" class="nav navbar-nav">
                        <li><a href="{% url 'index'%}">Home</a></li>
                        <li><a href="{% url 'index/#about'%}">About Us</a></li>
                        <li><a href="{% url 'service'%}">Service</a></li>
                        <li><a href="{% url 'index#review'%}">Review</a></li>
                        <li><a href="">Login</a></li>
                    </ul>
                </nav>
				<!-- /main nav -->
				
            </div>
        </header>
        <!--고정 네비 끝-->
		
		<main class="site-content" role="main">
		
        <!--페이지 메인 슬라이드 -->

			<div>여











				기<br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br>
								기<br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br>
								기<br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br>
								기<br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br>
				v
								기<br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br>










				에 넣







				어주세요</div>

		</main>
		
		<footer id="footer">
			<div class="container">
				<div class="row text-center">
					<div class="footer-content">
						<p>Copyright &copy; 2021 Multi Campus Uhdirogayahazo</p>
					</div>
				</div>
			</div>
		</footer>
		
		<!-- Essential jQuery Plugins
		================================================== -->
		<!-- Main jQuery -->
		<script src='{% static "js/jquery-1.11.1.min.js" %}'></script>
		<!-- Twitter Bootstrap -->
        <!--<script src="js/bootstrap.min.js"></script>-->
		<!-- Single Page Nav -->
		<script src='{% static "js/jquery.singlePageNav.min.js" %}'></script>
		<!-- jquery.fancybox.pack -->
		<script src='{% static "js/jquery.fancybox.pack.js" %}'></script>
		<!-- Google Map API -->
		<script src="http://maps.google.com/maps/api/js?sensor=false"></script>
		<!-- Owl Carousel -->
		<script src='{% static "js/owl.carousel.min.js" %}'></script>
        <!-- jquery easing -->
		<script src='{% static "js/jquery.easing.min.js" %}'></script>
        <!-- Fullscreen slider -->
		<script src='{% static "js/jquery.slitslider.js" %}'></script>
		<script src='{% static "js/jquery.ba-cond.min.js" %}'></script>
		<!-- onscroll animation -->
		<script src='{% static "js/wow.min.js" %}'></script>
		<!-- Custom Functions -->
		<script src='{% static "js/main.js" %}'></script>
    </body>
</html>